name: PHPStan

on: [pull_request]

jobs:
  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHPStan
        uses: docker://phpstan/phpstan

      - name: Run PHPStan
        run: |
          # Identificeer gewijzigde bestanden
          changed_files=$(git diff --name-only HEAD^..HEAD)

          # Filter PHP-bestanden
          php_files=$(echo "$changed_files" | grep '\.php$' || true)

          # Voer PHPStan uit op gewijzigde PHP-bestanden
          if [ -n "$php_files" ]; then
            phpstan analyse --level=7 --no-progress $php_files
          else
            echo "Geen PHP-bestanden gewijzigd. PHPStan wordt niet uitgevoerd."
          fi
