name: PHPStan

on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Of de versie die je nodig hebt

      - name: Install dependencies
        run: composer require --dev phpstan/phpstan

      - name: Run PHPStan on changed files
        run: |
          vendor/bin/phpstan analyse --level=7 --no-progress $CHANGED_FILES
        env:
          CHANGED_FILES: $(git diff --diff-filter=d main | grep '\.php$')
 
