name: PHPStan

on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Of de versie die je nodig hebt

      - name: Install dependencies
        run: composer require --dev phpstan/phpstan

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get changed PHP files
        id: get_changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD --diff-filter=d | grep '\.php$' || echo "")
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run PHPStan on changed files
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            vendor/bin/phpstan analyse --level=7 --no-progress $CHANGED_FILES
          else
            echo "No PHP files changed."
          fi
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}

