name: check_pull_request_code

on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Of de versie die je nodig hebt

      - name: Install dependencies
        run: composer require --dev phpstan/phpstan

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get changed PHP files
        id: get_changed_files
        run: |
          git diff --name-only origin/main --diff-filter=d | grep '\.php$' > changed_files.txt || echo "" > changed_files.txt

      - name: Debug changed files
        run: cat changed_files.txt

      - name: Run PHPStan on changed files
        run: |
          CHANGED_FILES=$(cat changed_files.txt)
          if [ -n "$CHANGED_FILES" ]; then
            vendor/bin/phpstan analyse --level=7 --no-progress $CHANGED_FILES
          else
            echo "No PHP files changed."
          fi

